# Use the official OpenJDK image as a parent image
FROM openjdk:11

# Set the working directory
WORKDIR /app

# Copy the Maven Wrapper and pom.xml to the image
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

# Copy the source code
COPY src src

# Build the application
RUN ./mvnw clean package -DskipTests

# Run the JAR file
ENTRYPOINT ["java", "-jar", "/app/target/gatewayserver-0.0.1-SNAPSHOT.jar"]
